# DataSource Config
spring:
  application:
    name: minio-action
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minio?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: gzm2001..
#mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath:/mapper/*.xml
  # 配置Mybatis数据返回类型别名（默认别名为类名）
  type-aliases-package: org.leocoder.action.domain
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#配置控制台打印日志Debug
logging:
  level:
    org.leocoder.action.mapper: debug
server:
  port: 8884



# 对象存储服务配置
file:
  # MinIO自搭建对象存储服务
  minio:
    endpoint: http://192.168.4.100:9000 #存储服务域名
    accessKey: UOtFyn9q8TC8l4SZmmC1 #AccessKey
    secretKey: akSAxk6WIZbBUYoSufItLWtVCcGaJdHI6n2huSmd #SecretKey
    bucket: leocoder   #存储桶名称